export DX_HDL_DIR := /home/julongjian/Repository/dx_hdl
export PROJECT_NAME := project_example
export IGNORE_VERSION_CHECK := 1
MODE := incr

M_DEPS +=
LIB_DEPS +=

include ${DX_HDL_DIR}/scripts/project/project_xilinx.mk
